<?php

namespace LBcrew\SiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SiteController__JMSInjector
{
    public static function inject($container) {
        $instance = new \LBcrew\SiteBundle\Controller\SiteController();
        return $instance;
    }
}
