<?php

namespace LBcrew\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TropheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TropheRepository extends EntityRepository
{
}
