<?php

namespace LBcrew\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
}
