<?php

namespace LBcrew\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * genreVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreVideoRepository extends EntityRepository
{
}
