parameters:
#    l_bcrew_site.example.class: LBcrew\SiteBundle\Example

services:
#    l_bcrew_site.example:
#        class: %l_bcrew_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
