parameters:
#    mind_user.example.class: Mind\UserBundle\Example

services:
#    mind_user.example:
#        class: %mind_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
