<?php

namespace LBcrew\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InterUserStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterUserStatutRepository extends EntityRepository
{
}
