parameters:
#    l_bcrew_media.example.class: LBcrew\MediaBundle\Example

services:
#    l_bcrew_media.example:
#        class: %l_bcrew_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
