<?php

namespace Proxies\__CG__\LBcrew\MediaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class musique extends \LBcrew\MediaBundle\Entity\musique implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setArtisteMusique($artisteMusique)
    {
        $this->__load();
        return parent::setArtisteMusique($artisteMusique);
    }

    public function getArtisteMusique()
    {
        $this->__load();
        return parent::getArtisteMusique();
    }

    public function setAlbum($album)
    {
        $this->__load();
        return parent::setAlbum($album);
    }

    public function getAlbum()
    {
        $this->__load();
        return parent::getAlbum();
    }

    public function setDureeMusique($dureeMusique)
    {
        $this->__load();
        return parent::setDureeMusique($dureeMusique);
    }

    public function getDureeMusique()
    {
        $this->__load();
        return parent::getDureeMusique();
    }

    public function setAlbumMusique($albumMusique)
    {
        $this->__load();
        return parent::setAlbumMusique($albumMusique);
    }

    public function getAlbumMusique()
    {
        $this->__load();
        return parent::getAlbumMusique();
    }

    public function addGenresMusique(\LBcrew\MediaBundle\Entity\genreMusique $genresMusique)
    {
        $this->__load();
        return parent::addGenresMusique($genresMusique);
    }

    public function removeGenresMusique(\LBcrew\MediaBundle\Entity\genreMusique $genresMusique)
    {
        $this->__load();
        return parent::removeGenresMusique($genresMusique);
    }

    public function getGenresMusique()
    {
        $this->__load();
        return parent::getGenresMusique();
    }

    public function setCovertMusique(\LBcrew\MediaBundle\Entity\covertMusique $covertMusique = NULL)
    {
        $this->__load();
        return parent::setCovertMusique($covertMusique);
    }

    public function getCovertMusique()
    {
        $this->__load();
        return parent::getCovertMusique();
    }

    public function setTitreMedia($titreMedia)
    {
        $this->__load();
        return parent::setTitreMedia($titreMedia);
    }

    public function getTitreMedia()
    {
        $this->__load();
        return parent::getTitreMedia();
    }

    public function setDatePubMedia($datePubMedia)
    {
        $this->__load();
        return parent::setDatePubMedia($datePubMedia);
    }

    public function getDatePubMedia()
    {
        $this->__load();
        return parent::getDatePubMedia();
    }

    public function setNbVueMedia($nbVueMedia)
    {
        $this->__load();
        return parent::setNbVueMedia($nbVueMedia);
    }

    public function getNbVueMedia()
    {
        $this->__load();
        return parent::getNbVueMedia();
    }

    public function setDescripMedia($descripMedia)
    {
        $this->__load();
        return parent::setDescripMedia($descripMedia);
    }

    public function getDescripMedia()
    {
        $this->__load();
        return parent::getDescripMedia();
    }

    public function setTest($test)
    {
        $this->__load();
        return parent::setTest($test);
    }

    public function getTest()
    {
        $this->__load();
        return parent::getTest();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titre_media', 'date_pub_media', 'nb_vue_media', 'descrip_media', 'artiste_musique', 'album_musique', 'duree_musique', 'genres_musique', 'covert_musique');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}