<?php

namespace Proxies\__CG__\LBcrew\MediaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class media extends \LBcrew\MediaBundle\Entity\media implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitreMedia($titreMedia)
    {
        $this->__load();
        return parent::setTitreMedia($titreMedia);
    }

    public function getTitreMedia()
    {
        $this->__load();
        return parent::getTitreMedia();
    }

    public function setDatePubMedia($datePubMedia)
    {
        $this->__load();
        return parent::setDatePubMedia($datePubMedia);
    }

    public function getDatePubMedia()
    {
        $this->__load();
        return parent::getDatePubMedia();
    }

    public function setNbVueMedia($nbVueMedia)
    {
        $this->__load();
        return parent::setNbVueMedia($nbVueMedia);
    }

    public function getNbVueMedia()
    {
        $this->__load();
        return parent::getNbVueMedia();
    }

    public function setDescripMedia($descripMedia)
    {
        $this->__load();
        return parent::setDescripMedia($descripMedia);
    }

    public function getDescripMedia()
    {
        $this->__load();
        return parent::getDescripMedia();
    }

    public function setTest($test)
    {
        $this->__load();
        return parent::setTest($test);
    }

    public function getTest()
    {
        $this->__load();
        return parent::getTest();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'titre_media', 'date_pub_media', 'nb_vue_media', 'descrip_media');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}