parameters:
#    l_bcrew_messages.example.class: LBcrew\MessagesBundle\Example

services:
#    l_bcrew_messages.example:
#        class: %l_bcrew_messages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
