<?php

namespace LBcrew\CommentairesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * commentaires_photoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentaires_photoRepository extends EntityRepository
{
}
