<?php

namespace LBcrew\CommentairesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * commentairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentairesRepository extends EntityRepository
{
}
