<?php

namespace LBcrew\CommentairesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * commentaires_evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentaires_evenementRepository extends EntityRepository
{
}
